name: Build
on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install
      run: |
        curl https://pyenv.run | bash
        export PATH="/home/runner/.pyenv/bin:$PATH"
        eval "$(pyenv init -)"
        eval "$(pyenv virtualenv-init -)"
        pip install setuptools wheel 
        pip install tox tox-pyenv
    - name: test
      run: python -m tox